Config translations support
wirenboard/wb-mqtt-confed pull request #16
Opened 2021-09-07 06:09 UTC by KraPete

Title and descriprion translations are added to Editor.List RPC response. Translations should be defined in "translations" property of a schema.

2021-09-07 09:03 UTC, evgeny-boger approved these changes

2021-09-07 11:23 UTC, webconn commented
Давай тут ещё пример опишем (на основе `sample.schema.json`, например, `sample-translations.schema.json`), а лучше ещё и тесты сделаем, что корректно работают и старые, и новые схемы (с переводами и без)

2021-09-09 06:18 UTC, KraPete commented
Тесты тут давно никто не запускал. Ожидаемо, они не проходят. Добавил пример.

2021-09-09 09:14 UTC, webconn requested changes

2021-09-09 09:14 UTC, webconn commented on confed/sample-translations.schema.json
> +      "Just an example": "Пример описания"
Может, записывать их сюда по ключам `title` и `description`? Не очень хорошо использовать человекоориентированный текст как ключи, его могут поменять в одном месте и всё сломается

2021-09-10 06:18 UTC, KraPete commented on confed/sample-translations.schema.json
> +      "Just an example": "Пример описания"
Я сделал сейчас так, что все переводы любых строк в шаблоне лежат в "translations":"lang", где ключ - оригинальная строка, а значение - перевод. Так не надо задумываться, что какие-то строки надо одним способом задавать, а другие - другим.
Изначально сделал так для json-editor, т.к. там API поиска перевода `translateProperty(key)`, т.е. просто поиск по оригинальной строке. Когда стал названия добавлять, решил всё единообразно в одном месте хранить.

2021-09-10 12:26 UTC, webconn approved these changes

2021-09-13 13:14 UTC, KraPete commented
Rebase https://github.com/wirenboard/wb-mqtt-confed/pull/18

2021-09-13 13:14 UTC, closed without merging