Backport reload or restart
wirenboard/wb-mqtt-confed pull request #46
Opened 2023-05-03 11:00 UTC by ekateluv

Бэкпортирование функционала по restart-or-reload для бэкпортирования нового публикатора соединений

2023-05-05 04:46 UTC, KraPete approved these changes

2023-05-06 20:58 UTC, sikmir approved these changes
Backport of https://github.com/wirenboard/wb-mqtt-confed/pull/45

2023-05-10 08:55 UTC, webconn requested changes
А этот бэкпорт точно нужен? Тут же то же самое, что в master, можно просто fast-forward сделать и перенести версию 1.13 в релиз

2023-05-10 11:10 UTC, ekateluv commented
Решили просто передвинем ветку релиза на текущий мастер. Не будем делать бэкпорт

2023-05-10 11:10 UTC, closed without merging